import React from "react";
import { bindNodeCallback } from "rxjs";

class Rules extends React.Component {
    render() {

        const { list } = this.props;
        const cardStyle = {
            color: "black",
            backgroundColor: "#83D9DE",
            padding: "10px",
            fontSize:"16px",
            lineHeight: "26px",
            width: "600px",
            marginLeft: "15px"
        };
        return ( < >
            <div className = "card" style = { cardStyle } >
            <ol>
                <h2 style ={{fontWeight: "bold",}}> How to Play </h2>  
                <li> A random number, from 1 to 10, is generated by the computer </li>
                <li> You only have <a style ={{color: "red"}}>3 chances</a> to guess the number and beat the computer. </li>   
                <li> Dont worry, the computer will let you know if your guess was higher or lower than the random number. </li>  
            </ol>
            <p style ={{fontWeight: "bold",marginLeft:"12px"}}> Do you have what it takes to win ? </p> 
            </div>      
            </>

        );
    }
}

export default Rules;
