import React from "react";

class Rules extends React.Component {
    render() {

        const { list } = this.props;
        return ( 
            <>
            <ol >
            <h2>How to Play</h2>
            <li>A random number is generated by the computer</li>
            <li>You only have 3 chances to guess the number and beat the computer.</li>
            <li>Don’t worry, the computer will let you know if your guess was higher or lower than the random number.</li>
            <h3>Do you have what it takes to win?</h3>
            <p>Use the register button below to create an account so you can save your progress or log in if you already have one.</p>
            </ol >
            </>
        );
    }
}

export default Rules;